# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\nekoy\OneDrive - DigiPen Institute of Technology\Documents\GitHub\Project-Eternum-Engine"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\nekoy\OneDrive - DigiPen Institute of Technology\Documents\GitHub\Project-Eternum-Engine"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\ctest.exe" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\JetBrains\CLion 2025.1.4\bin\cmake\win\x64\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\nekoy\OneDrive - DigiPen Institute of Technology\Documents\GitHub\Project-Eternum-Engine\CMakeFiles" "C:\Users\nekoy\OneDrive - DigiPen Institute of Technology\Documents\GitHub\Project-Eternum-Engine\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\nekoy\OneDrive - DigiPen Institute of Technology\Documents\GitHub\Project-Eternum-Engine\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P "C:\Users\nekoy\OneDrive - DigiPen Institute of Technology\Documents\GitHub\Project-Eternum-Engine\CMakeFiles\VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eternum-engine-lib

# Build rule for target.
eternum-engine-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 eternum-engine-lib
.PHONY : eternum-engine-lib

# fast build rule for target.
eternum-engine-lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/build
.PHONY : eternum-engine-lib/fast

#=============================================================================
# Target rules for targets named eternum-engine

# Build rule for target.
eternum-engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 eternum-engine
.PHONY : eternum-engine

# fast build rule for target.
eternum-engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine.dir\build.make CMakeFiles/eternum-engine.dir/build
.PHONY : eternum-engine/fast

#=============================================================================
# Target rules for targets named eternum-tests

# Build rule for target.
eternum-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 eternum-tests
.PHONY : eternum-tests

# fast build rule for target.
eternum-tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/build
.PHONY : eternum-tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f "Eternum Engine\third_party\googletest\googlemock\CMakeFiles\gmock.dir\build.make" "Eternum Engine/third_party/googletest/googlemock/CMakeFiles/gmock.dir/build"
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f "Eternum Engine\third_party\googletest\googlemock\CMakeFiles\gmock_main.dir\build.make" "Eternum Engine/third_party/googletest/googlemock/CMakeFiles/gmock_main.dir/build"
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f "Eternum Engine\third_party\googletest\googletest\CMakeFiles\gtest.dir\build.make" "Eternum Engine/third_party/googletest/googletest/CMakeFiles/gtest.dir/build"
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f "Eternum Engine\third_party\googletest\googletest\CMakeFiles\gtest_main.dir\build.make" "Eternum Engine/third_party/googletest/googletest/CMakeFiles/gtest_main.dir/build"
.PHONY : gtest_main/fast

Eternum_Engine/src/Core/Runtime/Runtime.obj: Eternum_Engine/src/Core/Runtime/Runtime.cpp.obj
.PHONY : Eternum_Engine/src/Core/Runtime/Runtime.obj

# target to build an object file
Eternum_Engine/src/Core/Runtime/Runtime.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Core/Runtime/Runtime.cpp.obj
.PHONY : Eternum_Engine/src/Core/Runtime/Runtime.cpp.obj

Eternum_Engine/src/Core/Runtime/Runtime.i: Eternum_Engine/src/Core/Runtime/Runtime.cpp.i
.PHONY : Eternum_Engine/src/Core/Runtime/Runtime.i

# target to preprocess a source file
Eternum_Engine/src/Core/Runtime/Runtime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Core/Runtime/Runtime.cpp.i
.PHONY : Eternum_Engine/src/Core/Runtime/Runtime.cpp.i

Eternum_Engine/src/Core/Runtime/Runtime.s: Eternum_Engine/src/Core/Runtime/Runtime.cpp.s
.PHONY : Eternum_Engine/src/Core/Runtime/Runtime.s

# target to generate assembly for a file
Eternum_Engine/src/Core/Runtime/Runtime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Core/Runtime/Runtime.cpp.s
.PHONY : Eternum_Engine/src/Core/Runtime/Runtime.cpp.s

Eternum_Engine/src/Core/pch/pch.obj: Eternum_Engine/src/Core/pch/pch.cpp.obj
.PHONY : Eternum_Engine/src/Core/pch/pch.obj

# target to build an object file
Eternum_Engine/src/Core/pch/pch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Core/pch/pch.cpp.obj
.PHONY : Eternum_Engine/src/Core/pch/pch.cpp.obj

Eternum_Engine/src/Core/pch/pch.i: Eternum_Engine/src/Core/pch/pch.cpp.i
.PHONY : Eternum_Engine/src/Core/pch/pch.i

# target to preprocess a source file
Eternum_Engine/src/Core/pch/pch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Core/pch/pch.cpp.i
.PHONY : Eternum_Engine/src/Core/pch/pch.cpp.i

Eternum_Engine/src/Core/pch/pch.s: Eternum_Engine/src/Core/pch/pch.cpp.s
.PHONY : Eternum_Engine/src/Core/pch/pch.s

# target to generate assembly for a file
Eternum_Engine/src/Core/pch/pch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Core/pch/pch.cpp.s
.PHONY : Eternum_Engine/src/Core/pch/pch.cpp.s

Eternum_Engine/src/Systems/Input/InputSystem.obj: Eternum_Engine/src/Systems/Input/InputSystem.cpp.obj
.PHONY : Eternum_Engine/src/Systems/Input/InputSystem.obj

# target to build an object file
Eternum_Engine/src/Systems/Input/InputSystem.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Systems/Input/InputSystem.cpp.obj
.PHONY : Eternum_Engine/src/Systems/Input/InputSystem.cpp.obj

Eternum_Engine/src/Systems/Input/InputSystem.i: Eternum_Engine/src/Systems/Input/InputSystem.cpp.i
.PHONY : Eternum_Engine/src/Systems/Input/InputSystem.i

# target to preprocess a source file
Eternum_Engine/src/Systems/Input/InputSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Systems/Input/InputSystem.cpp.i
.PHONY : Eternum_Engine/src/Systems/Input/InputSystem.cpp.i

Eternum_Engine/src/Systems/Input/InputSystem.s: Eternum_Engine/src/Systems/Input/InputSystem.cpp.s
.PHONY : Eternum_Engine/src/Systems/Input/InputSystem.s

# target to generate assembly for a file
Eternum_Engine/src/Systems/Input/InputSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/Eternum_Engine/src/Systems/Input/InputSystem.cpp.s
.PHONY : Eternum_Engine/src/Systems/Input/InputSystem.cpp.s

Eternum_Engine/src/main.obj: Eternum_Engine/src/main.cpp.obj
.PHONY : Eternum_Engine/src/main.obj

# target to build an object file
Eternum_Engine/src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine.dir\build.make CMakeFiles/eternum-engine.dir/Eternum_Engine/src/main.cpp.obj
.PHONY : Eternum_Engine/src/main.cpp.obj

Eternum_Engine/src/main.i: Eternum_Engine/src/main.cpp.i
.PHONY : Eternum_Engine/src/main.i

# target to preprocess a source file
Eternum_Engine/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine.dir\build.make CMakeFiles/eternum-engine.dir/Eternum_Engine/src/main.cpp.i
.PHONY : Eternum_Engine/src/main.cpp.i

Eternum_Engine/src/main.s: Eternum_Engine/src/main.cpp.s
.PHONY : Eternum_Engine/src/main.s

# target to generate assembly for a file
Eternum_Engine/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine.dir\build.make CMakeFiles/eternum-engine.dir/Eternum_Engine/src/main.cpp.s
.PHONY : Eternum_Engine/src/main.cpp.s

Unit_Tests/SystemRegistryTests.obj: Unit_Tests/SystemRegistryTests.cpp.obj
.PHONY : Unit_Tests/SystemRegistryTests.obj

# target to build an object file
Unit_Tests/SystemRegistryTests.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/Unit_Tests/SystemRegistryTests.cpp.obj
.PHONY : Unit_Tests/SystemRegistryTests.cpp.obj

Unit_Tests/SystemRegistryTests.i: Unit_Tests/SystemRegistryTests.cpp.i
.PHONY : Unit_Tests/SystemRegistryTests.i

# target to preprocess a source file
Unit_Tests/SystemRegistryTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/Unit_Tests/SystemRegistryTests.cpp.i
.PHONY : Unit_Tests/SystemRegistryTests.cpp.i

Unit_Tests/SystemRegistryTests.s: Unit_Tests/SystemRegistryTests.cpp.s
.PHONY : Unit_Tests/SystemRegistryTests.s

# target to generate assembly for a file
Unit_Tests/SystemRegistryTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/Unit_Tests/SystemRegistryTests.cpp.s
.PHONY : Unit_Tests/SystemRegistryTests.cpp.s

Unit_Tests/SystemTests.obj: Unit_Tests/SystemTests.cpp.obj
.PHONY : Unit_Tests/SystemTests.obj

# target to build an object file
Unit_Tests/SystemTests.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/Unit_Tests/SystemTests.cpp.obj
.PHONY : Unit_Tests/SystemTests.cpp.obj

Unit_Tests/SystemTests.i: Unit_Tests/SystemTests.cpp.i
.PHONY : Unit_Tests/SystemTests.i

# target to preprocess a source file
Unit_Tests/SystemTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/Unit_Tests/SystemTests.cpp.i
.PHONY : Unit_Tests/SystemTests.cpp.i

Unit_Tests/SystemTests.s: Unit_Tests/SystemTests.cpp.s
.PHONY : Unit_Tests/SystemTests.s

# target to generate assembly for a file
Unit_Tests/SystemTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/Unit_Tests/SystemTests.cpp.s
.PHONY : Unit_Tests/SystemTests.cpp.s

# target to build an object file
cmake_pch.hxx.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/cmake_pch.hxx.gch
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/cmake_pch.hxx.gch
.PHONY : cmake_pch.hxx.gch

# target to preprocess a source file
cmake_pch.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/cmake_pch.hxx.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/cmake_pch.hxx.i
.PHONY : cmake_pch.hxx.i

# target to generate assembly for a file
cmake_pch.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-engine-lib.dir\build.make CMakeFiles/eternum-engine-lib.dir/cmake_pch.hxx.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles\eternum-tests.dir\build.make CMakeFiles/eternum-tests.dir/cmake_pch.hxx.s
.PHONY : cmake_pch.hxx.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test
	@echo ... eternum-engine
	@echo ... eternum-engine-lib
	@echo ... eternum-tests
	@echo ... gmock
	@echo ... gmock_main
	@echo ... gtest
	@echo ... gtest_main
	@echo ... Eternum_Engine/src/Core/Runtime/Runtime.obj
	@echo ... Eternum_Engine/src/Core/Runtime/Runtime.i
	@echo ... Eternum_Engine/src/Core/Runtime/Runtime.s
	@echo ... Eternum_Engine/src/Core/pch/pch.obj
	@echo ... Eternum_Engine/src/Core/pch/pch.i
	@echo ... Eternum_Engine/src/Core/pch/pch.s
	@echo ... Eternum_Engine/src/Systems/Input/InputSystem.obj
	@echo ... Eternum_Engine/src/Systems/Input/InputSystem.i
	@echo ... Eternum_Engine/src/Systems/Input/InputSystem.s
	@echo ... Eternum_Engine/src/main.obj
	@echo ... Eternum_Engine/src/main.i
	@echo ... Eternum_Engine/src/main.s
	@echo ... Unit_Tests/SystemRegistryTests.obj
	@echo ... Unit_Tests/SystemRegistryTests.i
	@echo ... Unit_Tests/SystemRegistryTests.s
	@echo ... Unit_Tests/SystemTests.obj
	@echo ... Unit_Tests/SystemTests.i
	@echo ... Unit_Tests/SystemTests.s
	@echo ... cmake_pch.hxx.gch
	@echo ... cmake_pch.hxx.i
	@echo ... cmake_pch.hxx.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P "C:\Users\nekoy\OneDrive - DigiPen Institute of Technology\Documents\GitHub\Project-Eternum-Engine\CMakeFiles\VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

